FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /shareddata

COPY ./publish .

ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000

ENTRYPOINT dotnet WebApplication2.dll